/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'christopherholmes' at '19/10/15 17:54' with Gradle 2.6
 *
 * @author christopherholmes, @date 19/10/15 17:54
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
